ubccr/supremm

- assets/mongo_setup.js
To run the setup script to connect to a mongo instance on a remote
host, then use the following syntax:
mongo --host REMOTE_HOST assets/mongo_setup.js
> Mongo setup now works with remote hosts.

- supremm/indexarchives.py
- supremm/ingest_jobscripts.py
- supremm/outputter.py
- supremm/preprocessors/SlurmProc.py
- supremm/summarize.py
- supremm/summarize_jobs.py
captureWarnings does not exist in 2.6 logging
filter() must use positional arguments in 2.6
> Python 2.6 support

- README.md
- setup.cfg
- setup.py
- Update build dependency documentation
- setup.cfg file appends dist to rpm name and uses correct rpm requirements for Centos 6
- add RPM build requirements, license and description
- Update RPM version number
> Add support for building Centos 6 RPMs.

- supremm/scripthelpers.py
The db settings were incorrectly being preserved between different
calls to the getdbconnection() function.
> Fix isssue with db help function default settings.

- supremm/ingest_jobscripts.py
Remove use of keyword arguments with decode() which makes the usage compatible with Python 2.6.x
> Python 2.6 fix

- supremm/plugin.py
- supremm/preprocessors/SlurmProc.py
- supremm/summarize.py
This resolves the TODO in the code to abstract out the preprocessor
plugin details from the main handler code. Preprocessors now have a
mandatory results() function, the return value of which will be added
to the job summary. Preproc errors are also added to the job summary
doc too.
> Allow preprocs to output results.

- supremm/plugins/CpuUsage.py
Seen on a few nodes on the CCR HPC resource where the CPU information
dissapears from the kernel.percpu metrics. Handle this case gracefully.
> Handle rare case where kernel.percpu metrics missing.

- supremm/plugins/MemBwTimeseries.py
- supremm/plugins/SimdInsTimeseries.py
Plugin grabbed wrong value from description array, which made dev and name catigories be empty.
> Fix issues in timeseries plugins

- setup.cfg
- setup.py
Unfortunately setup tools do not support this natively, so we use a workaround
that generates an install script that has %config(noreplace) for all files in the
config directory.
> Ensure config files are marked %config in spec file.

- supremm/supremm-setup
- supremm/xdmodstylesetupmenu.py
- Default values are populated from the existing config file (if present)
- Now have to press enter after selecting menu options (to match xdmod-setup
behaviour).
- Menu prompt text modified to be similar to xdmod-setup prompt text.
- Warning message displayed if user specifies an archive directory that does not
exist.
- Instructions on how to specify an empty path for the job script files.
> Updates to the setup script in resopnse to testing user feedback

- assets/mongo_setup.js
- supremm/plugin.py
- supremm/plugins/BlueWaters.py
- supremm/plugins/Catastrophe.py
- supremm/plugins/ClksTimeseries.py
- supremm/plugins/CpuPerfCounters.py
- supremm/plugins/CrayGemini.py
- supremm/plugins/GpuUsage.py
- supremm/plugins/Network.py
- supremm/plugins/NodeMemoryUsage.py
- supremm/plugins/NumaMemoryUsage.py
- supremm/plugins/UncoreCounters.py
- supremm/preprocessors/HardwareInventory.py
Timeseries Metrics:
- Added Clock Ticks timeseries
- Added AMD metrics to SIMD timeseries
Summary Metrics:
- Updated hardware-counter plugins to support AMD counters.
- Allow GPU plugin to run without mem active metric.
- Allow network metrics to only have bytes and not packets.
- Added node-level memory usage plugin; renamed memory usage to numa to
reduce potential confusion between the two plugins
Preprocessors:
- Update hardware inventory preproc.
The schema version is updated to reflect the new metrics.
> Added support for metrics from BlueWaters

- supremm/plugins/ClksTimeseries.py
- supremm/plugins/CpuUserTimeseries.py
- supremm/plugins/SimdInsTimeseries.py
- supremm/subsample.py
Recent versions of numpy complain if you don't use int indexes. This
change ensures that all indexes are cast to the correct type before
use.
> Fix code that causes deprecation warnings.

- supremm/subsample.py
Change default number of datapoints from 100 to 50 so that the timeseries data is smaller. With 100
datapoints the data size could exceed the MongoDB document size limit of 16MiB if the compute
nodes had 32 cores per node or more.
> Reduce default number of datapoints in timeseries data.

- supremm/plugins/Catastrophe.py
- supremm/plugins/ClksTimeseries.py
- supremm/plugins/CpuPerfCounters.py
- supremm/plugins/MemBwTimeseries.py
- supremm/plugins/SimdInsTimeseries.py
- supremm/plugins/UncoreCounters.py
- supremm/preprocessors/PerfEvent.py
The preprocessor checks the perfevent active flag rather than
having to d it redundantly for each plugin. Also the plugins that
only need the first and last values can retrieve the active status
for the whole job.
> Now use preprocessor to check the perfevent active flag.

- supremm/summarize.py
If a first-last plugin returned false on the first callback, then it would be
incorrectly marked as uninitialized rather than failed. Hence the plugin output
(which should be a valid error code) would not appear in the summary record.
> Fix output issue for first-last type plugins.

- MANIFEST.in
- setup.cfg
- setup.py
- supremm/pypmlogextract/dlsymdefs.pxd
- supremm/pypmlogextract/pypmlogextract.pyx
Calling fork from an MPI process causes spurious segfaults. Implement
a cython extension that will call a dynamic library version of
pmlogextract.
> Add the pypmlogextract module

- supremm/pcparchive.py
- supremm/summarize_jobs.py
- supremm/summarize_mpi.py
- supremm/xdmodaccount.py
Allow the tasks to be handed out as nodes finish the previous one.
Should allow for better packing.
Also, include a flag to use a library version of pmlogextract.  Suggest
usage of this when running in MPI mode since forking from an MPI task
has shown to cause segfaults in some MPI implementations.
Change the logging for mpi jobs.  Each task has its own log file. printf
from the dlopened pypmlogextract will not be captured.  That fix is a WIP.
> Master/Worker mode for summarize_mpi.py

- supremm/summarize_jobs.py
- supremm/summarize_mpi.py
Add the following syntax to config.json under the resource section:
"plugin_blacklist" : ["SlurmProc", "Gpfs", "GpfsTimeseries"]
"plugin_whitelist" : ["SlurmProc", "Gpfs", "GpfsTimeseries"]
Only one or the other should be used. Whitelist is highest
priority.  Affects both preprcs and plugins.
> Allow plugins to be enabled/disabled per resource

- supremm/pcparchive.py
- supremm/summarize_mpi.py
- supremm/xdmodaccount.py
Helps to have these in the tree so we don't have to apply a diff each time we reinstall. But
lump them all together to make it easier to revert when merged back into master.
Don't process jobs that would take a really long time, but mark
in the MongDB the reason.  These values probably should be configurable.
Also includes a few BW specific changes:
-trimming the last 60 seconds to deal with counter reset in epilog
-simplifying the job query since we don't have job start/end records
Also, revert the change of job ordering by size.  This caused resource contention during processing.
> A few BW specific changes

- supremm/plugins/CpuUsage.py
- supremm/plugins/NodeMemoryUsage.py
- The CPU plugin now can use the per-node CPU usage values if
the per-cpu values are absent.
- The Node Memory plugin summarizes the node-level memory usage
information.
> Added support for node-level CPU and memory metrics.

- supremm/outputter.py
- supremm/supremm-setup
The published documentation (and defaults for the interactive script) both
incorrectly spceified that the database engine setting was 'type', however the
code was expecting to see 'db_engine'. Now support either setting, with db_engine
as the preference.
> Output configuration supports 'type' as synonym for 'db_engine'

- supremm/outputter.py
The _id value for timeseries documents was not stored correctly on Centos 6.8
with the EPEL versions of mongodb 2.4.14. This results in the timeseries
information not being shown in the XDMoD Job Viewer.
> Fix missing timeseries document _id.

- supremm/preprocessors/HardwareInventory.py
Fix bug in hardware inventory preprocessor that throws an exception
if the cpu metrics are missing.
> HardwareInventory: handle missing cpu metrics.

- supremm/indexarchives.py
If there were no directories checked in the old format, t4 and t3
were not set. This lead to an exception and no further
processing was done. Hidden by the lack of scoping for loop
variables in python.
> Index archives fix

- supremm/proc_common.py
- tests/getoptionstest.py
- The -t option was incorrectly being used for both threads and tag
options.
- Change the default max duration to 10 days.
> Fix the -t option. Fix default max_duration

- assets/modw_supremm.sql
- migrations/1.0-1.1/modw_supremm.sql
- supremm/xdmodaccount.py
The job-level and node-level archive data are now split into different
tables. This significantly improves the performance of the job archive
queries.
> Change layout of archive tables to improve performance.

- supremm/errors.py
- supremm/proc_common.py
- tests/getoptionstest.py
- tests/summarizetest.py
- The maximum node time for a job can now be specified. This causes
long large jobs to be skipped.
- Also add tests for the new code.
> Added max node time limit and corresponding error message.

- supremm/plugins/MemBwTimeseries.py
- supremm/plugins/MemUsageTimeseries.py
- supremm/plugins/TotalMemUsageTimeseries.py
- supremm/subsample.py
Recent numpy versions deprecated using anything apart from a int to index a numpy
array. This change explictly sets the correct data type for the array indexes.
> Update array access for compatibility with numpy 1.12

- Dockerfile
- setup.py
- shippable.yml
This change adds a Dockfile that includes the build dependencies for
a Centos 7 install. The shippable.yml runs a test install and runs the
unit tests and code coverage report.
One minor change to the setup.py to allow the unit tests to work with
nosetests.
> Add support for shippable builds.

- setup.py
- shippable.yml
The changes to the setuptools config that was done to enable
compatibility with python nose tests broke the excutuable scripts that
are installed. This reverts these changes and (temporarily) removes the
unit testing from running automatically in the CI build. An exra step in
the CI build has been added to check that the scripts can execute.
> Revert setuptools changes.

- CHANGELOG.md
- supremm/outputter.py
- supremm/xdmodaccount.py
- Updated text content of indexarchives debug message to clarify
meaning of ignored archives.
- Fix issue with timeseries documents not being saved with the Centos 6
EPEL version of MongoDB (2.4). It is likely that this issue affects
newer versions of MongoDB too.
> Minor bug fixes

- supremm/supremm_testharness.py
Add command-line option `-c --config` to specify a custom config file for the testharness.
> Add option to specify config file to testharness

- config/templates/pmlogger/pmlogger-supremm.config
This is extremely minor.  The default template would produce a warning.  Only tested in docker test environment.
preprocessor cmd: /usr/libexec/pcp/bin/pmcpp -rs /etc/pcp/pmlogger/pmlogger-supremm.config -I /var/lib/pcp/config/pmlogger
Warning [/etc/pcp/pmlogger/pmlogger-supremm.config, line 168]
Problem with lookup for metric "mem.numa.util.NFS_unstable" ... logging not activated
Reason: Unknown metric name
> Minor fix for metric name mem.numa.util.NFS_Unstable

- Dockerfile
- supremm/preprocessors/SlurmProc.py
Return the process names ordered by frequency. This typically will result in the parallel processes appearing at the begining of the list and the stage-in and stage-out processes closer to the end.
> Sort procs by count

- Dockerfile
The docker that runs in shippable does not support the cap_set_file
API that is needed by the httpd RPM. This means that it is not
possible to update the httpd RPM in shippable.
The plan going forward is to manage the software versions in
the 'FROM' docker image.
>   Do not automatically update to latest.

- tests/integration_tests/bootstrap.sh
Use a glob to find the rpm to install for shippable integration tests so it doesn't break on version or other small changes
> Fix shippable rpm install

- src/supremm/summarize_jobs.py
The subprocesses were not all being `join()`ed due to a typo in the code. Also fixed the (minor) pylint warnings generated by this file.
> Fix bug joining child processes

- src/supremm/preprocessors/SlurmProc.py
Profiling has shown that the SlurmProc preprocessor accounts for over 30% of the long-term time of summarize_jobs. This PR makes optimizations which reduce the total time spent in this preprocessor by around a factor of 3.
> SlurmProc preprocessor performance tuning

- src/supremm/outputter.py
For complete json output, create file if it doesn't exist. Only open
the file when we need to write to it (not during the whole time
processing is happening). Use %r in file name to substitute resource
name.
> Tweaks to file outputter

- src/supremm/puffypcp/puffypcp.pyx
The mongo serialization code does no understand numpy float32 objects. This code change reverts back to the original (pre-puffypcp) behaviour so that all data are returned as doubles (which are understood by the mongo library).
> Use 64 bit floats for puffypcp

- src/supremm/summarize_jobs.py
- tests/integration_tests/integration_plugin_api.py
- tests/integration_tests/integration_test.bash
- tests/integration_tests/throwing_plugin.py
Moves the call to Summary.get() inside the current summarize try/catch blocks to properly handle exceptions within a plugin results() method.
Add mock plugins and tests to the plugin api integration tests which throw exceptions in different areas of the plugin, verifying that this does not cause an exception in the overall summarize_jobs run.
> Fix plugin results() exception handling

- src/supremm/summarize_jobs.py
Condition waits with no timeouts do not handle signals due to a bug in
python, so need to manually iterate over the pool map and specify a
timeout.
600 second timeout is arbitrary, all that matters is that there's a number there instead of unbounded for it to catch the signal.
> Initial workaround to allow SIGINT with multiproc pool

- config/templates/pmlogger/pmlogger-supremm.config
In updating the pmlogger config template, I lost one of Trey's
changes that fixed a typo.
> Fix a typo in the pmlogger config

- src/supremm/assets/modw_supremm.sql
- src/supremm/indexarchives.py
- src/supremm/migrations/1.0-1.1/modw_supremm.sql
- src/supremm/xdmodaccount.py
- tests/testPcpArchiveProcessor.py
Update the archives_joblevel table to store identifying information
for job array jobs and update the archive indexer to populate this.
> Update job id parsing for job arrays

- src/supremm/summarize_mpi.py
MPI version was broken because it was missing the output database API update.
> Missed API change in MPI code

- src/supremm/linuxhelpers.py
- src/supremm/preprocessors/PerfEvent.py
- src/supremm/summarize.py
If a pre-processor throw an exception then the hostend() function may not be called. This leaves the preprocessor in an inconsistent state. This change ensures that the hostend() is always called. Also an update to the `parsecpusallowed` to throw the right exception (this type of exception is handled already in the SlumProc) and extra defensive checks for the PerfEvent preproc.
> Robustness improvements for pre-processors

- src/supremm/Job.py
- src/supremm/pcparchive.py
When using the indexarchiver in fast_index mode the indexer does not acutally try to open the job begin and end pcp archives instead it just uses the presence of the archive on disk. This means that corrupt archives can end up in the index and be accessed at summary time. This change ensures that any corrupt archives are not processed.
Corrupt archives are logged at warning level and in the job summary doc.
> Remove corrupt job begin and end archives from processing

- config/templates/pmlogger/control
- config/templates/slurm/slurm-epilog
- config/templates/slurm/slurm-prolog
Also add in the definitions of the various `$log*` variables that were referenced in the example.
> Update templates for new archive layout.

- Dockerfile
- README.md
- setup.cfg
- tests/integration_tests/bootstrap.sh
- tests/integration_tests/integration_test.bash
- tests/integration_tests/supremm_setup_expect.py
Update the CI build to use the current XDMoD release, which is based on
the Centos 7.6.1810. There are a couple of minor updates to the test
harness to use the new XDMoD version.
This also switches the PCP dependency to be the version available in
the official Centos repository.
> Update CI build and RPM deps to official PCP version.

- src/supremm/preprocessors/SlurmProc.py
The slurm preprocessor logs errors at every timestamp for every process that
has problems. For jobs that have lots of processes the number of error messages
can exceeed the limt. This change switches to deduplicating the messages and
omits the process id from the message.
> Consolidate error logs for slurm proc

- src/supremm/ingest_jobscripts.py
- src/supremm/supremm_setup.py
- src/supremm/xdmodstylesetupmenu.py
- tests/integration_tests/bootstrap.sh
- tests/integration_tests/integration_test.bash
- tests/integration_tests/supremm_setup_expect.py
The jobs scripts are stored in datestamped directories. The original
code used the datestamp as the job's start time when looking up the job
information in the database. This change allows the datestamp to be
interpreted as either the submit day, start day, end day or for
the datestamp to be ignored completely.
The user facing documentation for this change is in https://github.com/ubccr/xdmod-supremm/pull/222
> Add support for specifying the meaning of the job script datestamp.

- src/supremm/supremm_testharness.py
Use the filename as the nodename in the testharness. This gives
better control over the test scenario
> Improve test harness

- src/supremm/supremm_setup.py
This code was a workaround for very early versions of the mongo shell
that did not recognise the mongodb uri syntax.
> Recent versions of mongo shell support the uri syntax

- src/supremm/indexarchives.py
If the pcp archive indexing took longer than the database
connection timeout then the indexarchives script would hang when
trying to do the database write. I would have assumed that the
database connection library would throw a timeout exception, but
this is not seen and the software just hangs.
This change just creates the database connection just before it
is needed for the write.
> Only open database connection when needed.

- src/supremm/plugins/LustreTimeseries.py
This generates timeseries plots that show under the 'Parallel Filesystem
traffic' tab.
> Add plugin for timeseries plots of lustre timeseries data.

- Dockerfile
The version of pip we were using to pull in the development dependencies
did not understand the difference between python 2 and 3. Hence it was trying
to pull incompatible versions of the dependencies.
> Update pip version to 20.

- src/supremm/ingest_jobscripts.py
This was in my local changes but somehow got missed during past merges.   This is the type of log message trying to avoid:
```
Aug 15 04:00:10 xdmod-test ingest_jobscripts:  cur.execute(self.query, qdata)
Aug 15 04:00:10 xdmod-test ingest_jobscripts: 
Aug 15 04:00:10 xdmod-test ingest_jobscripts: 2020-08-15T04:00:10 [WARNING] /usr/lib64/python2.7/site-packages/supremm/ingest_jobscripts.py:74: Warning: Duplicate entry '36106174' for key 'PRIMARY'
```
> Avoid duplicate warnings when ingesting job scripts

- src/supremm/plugins/CpuPerfCounters.py
Switch to using numpy.isfinite (which checks for Nan and Infinity). Previously
we wre checking for Nan, but this did not handle the Infinity error case.
> Tighten up check for corrupt performance counter values.

- src/supremm/ingest_jobscripts.py
If the jobscript mode was set to define timestamp_mode then the code
generated sql with a syntax error. This caused jobscript data to be erroneously
replaced with a '0'.
> Fix jobscript ingestion sql.

- src/supremm/plugins/CpuPerfCounters.py
Handle case where a subset of the perf counters had erroneous values. An example
of when this can happen is if some of the counters are multiplexed and
do not have a high enough duty cycle to produce accurate data.
This one would have been caught in 1.4.0 but missed in 1.4.1.
> Fix another edge case error handling in the Performance Counter plugin.

- src/supremm/config.py
While doing development I needed a way to store and modify the SUPREMM configs in my home directory and the code was installed into a virtualenv and so the solution I landed on was setting `SUPREMM_CONFIG_DIR` environment variable.
> Allow defining path to config via SUPREMM_CONFIG_DIR

- src/supremm/supremm_update
The example supremm_update script had inconsistent commandline
flags between the indexarchives step and the summarization.
This updates the default commandline for the indexarchives to be
consistent: quiet logging mode and multithreaded scanning.
> Use multithreaded archive indexing by default.

- src/supremm/xdmodaccount.py
This enabled autocommit for the sql queries that updates the XDMoD
table that records jobs that have been processed. This is to mitigate a
problem observed when a connection times out: the code tries to rerun the
queries, but gets a lock wait timout as the first attempt is waint to be
committed (and can't becouase the connection has timedout).
> Enable autocommit for markasdone.

- src/supremm/pcpcinterface/pcpcinterface.pyx
- src/supremm/preprocessors/Proc.py
I've been working with the latest SUPREMM beta on RHEL 8, and have found a bug that was causing missing/erroneous data on the Job Viewer page under the Executable Information tab.
The root cause of the problem is that when the module is pulling strings from PCP via pmlogextract, it's getting them as byte arrays, and apparently (at least) with python3.6, using str() on byte array "foo" encodes the resulting string as the literal "b'foo'".  This errant string then doesn't match the string "foo" and causes the missing data.
There are minor fixes to:
src/supremm/pcpcinterface/pcpcinterface.pyx
replacing the three occurrences of str(foo) with str(foo, 'utf-8')
and a fix to src/supremm/preprocessors/Proc.py
to remove a now unnecessary str() call due to the above change.
> Fix encoding of string data from PCP.

- src/supremm/assets/mongo_setup.js
This PR fixes the mongo_setup.js script to populate the schema definition with the appropriate function based on the Mongo shell version.
This change is necessary because the update() function is deprecated in versions of the Mongo shell greater than 5.0.
These changes were tested with successful results on both Mongo 4.4 and Mongo 6.0.
> Support setup for different versions of Mongo

- src/supremm/config.py
- src/supremm/supremmconf.py
This PR is the same as [this PR](https://github.com/ubccr/supremm/pull/258) for SUPReMM v2.0.
These changes improve the capabilities of the configuration check utility in supremmconf.py.
supremmconf.py
1.) Added debug flag
2.) Added flag to specify configuration path
3.) Can now print entire configuration
4.) Better handling for invalid sections or items
5.) Removed UTF-8 encoding for Python 3 version
config.py
1.) Added str method for easier printing
Tested on Rocky 8, Python 3.6.8
> Updates to configuration check utility for Python 3

- config/config.json
- src/supremm/xdmodaccount.py
This is needed for proper job array support see also pull requests in the xdmod and xdmod-supremm and xdmod-xsede code base.
> Add support for configurable job uniqueness.

- src/supremm/datasource/pcp/pcpsummarize.py
- src/supremm/datasource/prometheus/promsummarize.py
- tests/component/runtests.sh
This change is necessary for SUPReMM to work with the changes made in https://github.com/ubccr/xdmod-supremm/pull/346.
If this field is not present in the summarization record, then the Job Performance module assumes the summarization record was generated from PCP data. This behavior ensures backward compatibility with summarization records that do not contain a 'datasource' field because PCP was the only officially supported data source prior to SUPReMM v2.0.0.
> Add 'datasource' field to output summarization record
