ubccr/supremm

supremm/ingest_jobscripts.py, supremm/scripthelpers.py
Fix issue where the ingest_jobscripts had not been updated to use
the config helper functions.
Also ensure data is committed to the database before script exit
=> ingest_jobscripts now uses correct config.

supremm/pcparchive.py
The job-X-begin and job-X-end archives are created at job start and end time by
the resource manager prolog and epilog scripts. Ensure that these archives are
always included in the combined job output archive.
=> Use the job-X-begin and job-X-end archives to compute times

supremm/plugins/CpuUserTimeseries.py
If the CPUs allowed information is available, then only use these
CPUs in the timeseries plots.
=> Only show CPUs that the job used in the timeseries data.

supremm/plugins/Nfs.py, supremm/plugins/NfsTimeseries.py
Just includes read and write bytes at the moment.
=> Add nfs timeseries and summary processors.

supremm/summarize.py
- Fix memory leak when pcp library calls threw exceptions
- Ensure description parameter in process() call always has correct indom
information even if the indoms have changed during the archive.
- Improve error handling for missing indoms
=> Bug fixes for framework code

supremm/summarize.py
Can now use metrics with string instances.
=> Added support for string metrics

supremm/errors.py, supremm/plugin.py
Seen with filesystem mount points where they can appear and disappear during a
job. For the time being the corresponding data is marked with an error.
=> Handle case where devices disappear during a job.

supremm/indexarchives.py
The existing archive structure will still work. Now also
supports stored in directories in the format:
[pcp_log_dir]/[HOSTNAME]/[YYYYMM]/
where HOSTNAME is the hostname of the node and YYYYMM
the 4-digit year and month.
The indexer will only descend into directories that have
a timestamp that meets the min date.
=> Add support for filtering based on directory name

config/config.json, supremm/outputter.py
Rename dbhost config to uri and give examples of what a URI would look like - supports mongodb auth
=> Mongodb auth support via connection URI

assets/mongo_setup.js, supremm/plugins/BlockTimeseries.py, supremm/plugins/MemBwTimeseries.py, supremm/plugins/TotalMemUsageTimeseries.py
Added:
- memory bandwidth
- block device IO
- total memory usage.
also update schema documentation
=> Added timeseries metrics

supremm/indexarchives.py
The os.walk() command runs stat() on every file and directory in the tree. On
most parallel filesystems and network attached storage, these metadata
operations are time consuming. Switch the code to use listdir and rely on the
known filesystem layout to determine which files to open.
=> Use os.listdir to get directory listing.

supremm/supremm_testharness.py
The test harness script runs the plugins on the provided PCP archive.
This allows plugins to be tested independently of the full job database.
=> Added barebones test harness.

supremm/summarize_mpi.py, supremm/xdmodaccount.py
Only process new jobs when using a time range
=> New -N option for summarize_mpi.py

supremm/summarize_jobs.py, supremm/summarize_mpi.py
Adds a text tag to the mongo document for each job processed under
this summarization task.
=> Add -t flag to summarize_mpi.py and summarize_jobs.py

assets/mongo_setup.js
First pass at filling the schema documentation for the summary schema.
=> Update schema documentation.

supremm/plugins/BlueWatersCpu.py
Underlying counters are 48 bits.  Try to determine if they rolled over within some realistic threshold.
=> Check for rollover in BW CPUuser

supremm/pcparchive.py, supremm/summarize_jobs.py, supremm/summarize_mpi.py
If more than 95% of the nodes have data then process the job.
=> Add support for processing jobs with missing archives.

supremm/pcparchive.py, supremm/summarize_mpi.py, supremm/xdmodaccount.py
Jobs that have no nodes
Debugging information to check number of processes per node
Reconnect to DB if the connection times out
=> Some more fixes to deal with bluewaters issues

supremm/pcparchive.py, supremm/summarize_mpi.py, supremm/xdmodaccount.py
Depends on #82 being merged first
=> Parameter to specify the largest job (nodecount) to process

supremm/preprocessors/HardwareInventory.py
- The Hardware Inventory preprocessor will now try to use the hinv.ncpus
metric if the kernel.percpu values are absent.
- Also added an output for the preproc so that the cpu core count data is
logged in the summary document.
=> Hardware Inventory preproc can use hinv metric if avail.

supremm/indexarchives.py
Will descend into directories that are in the form YYYY/MM/DD and only process those directories / files that have timestamps in range.
=> Added ability to process YYYY/MM/DD directories

assets/mongo_setup.js
- Added more verbose help text for many metrics
- Fixed the incorrect data type for process_memory.usageratio
- eslint tidy up.
=> Update the schema description doc.

CHANGELOG.md, assets/mongo_setup.js, setup.py, supremm/indexarchives.py, supremm/outputter.py, supremm/plugin.py, supremm/plugins/CpuUsage.py, supremm/plugins/NfsTimeseries.py, supremm/plugins/NodeMemoryUsage.py, supremm/plugins/SlurmCgroupMemory.py, supremm/preprocessors/HardwareInventory.py, supremm/supremm-setup
Merge master into the bluewaters branch. This should make diffs easier to understand
=> Bluewaters merge

assets/mongo_setup.js, supremm/plugin.py, supremm/plugins/Catastrophe.py, supremm/plugins/CpuPerfCounters.py, supremm/plugins/CpuUserTimeseries.py, supremm/plugins/GpuUsage.py, supremm/plugins/GpuUsageTimeseries.py, supremm/plugins/MemBwTimeseries.py, supremm/plugins/Network.py, supremm/plugins/SimdInsTimeseries.py, supremm/plugins/UncoreCounters.py, supremm/preprocessors/PerfEvent.py
This includes:
- a new perfevent preprocessor to more efficiently handle perf counters
- New GPU timeseries
- changes to the perf plugins to use the new preprocessor.
=> Added new plugins from the BW workload analysis.

supremm/proc_common.py, supremm/summarize_mpi.py, tests/getoptionstest.py
Debug output is disabled by default.
=> Added commandline option to enable process dump debug output.

supremm/plugins/CpuUsage.py
The effective CPU metric counts the number of CPU cores that
had more than 5% overall usage. The statistics for these cores
is then calculated.
Also fix labelling error for the case where the percpu metrics
are absent.
=> Added effective CPU metrics.

supremm/supremm_testharness.py
Add command line flag to specify which plugins are included;
find the overall start and end times for the pcp archives.
=> Add features to supremm test harness

.pylintrc, shippable.yml, supremm/__init__.py, supremm/batch_acct.py, supremm/indexarchives.py, supremm/rangechange.py, supremm/summarize.py, supremm/xdmodaccount.py
Add default pylintrc for the project. Fix the pylintrc errors.
=> Add pylint to CI tests.

supremm/xdmodaccount.py
We have observe a rare database connection timeout when running indexarchives scanning data on a slow network attached filesystem.
This change will try to reconnect to the MySQL database if the driver throws an operational error. A log message at ERROR level is displayed if this code path runs.
=> Database reconnect on timeout.

AUTHORS, README.md, setup.py, shippable.yml
Update README to reflect setuptools changes and to provide more accurate instructions on installing in a conda environment.
Clean up shippable.yml and add step to remove supremm rpm package before testing source install.
Update AUTHORS file.
=> Docs updates

src/supremm/indexarchives.py
If a directory cannot be read due to access permissions then log the error and continue to process.
=> Log and continue on OSError

shippable.yml, src/supremm/ingest_jobscripts.py, tests/integration_tests/bootstrap.sh
Add support for XDMoD 8.0.0 job script schema. Also tidy up some existing pylint warnings in the file.
=> Add support for XDMoD 8.0.0 job script schema

config/templates/hotproc/hotproc.conf, config/templates/slurm/slurm-epilog, config/templates/slurm/slurm-prolog, setup.py
Update some of the templates based on user feedback to be
more clear and add some steps that were missing from the configuration.
=> Update some PCP config templates

src/supremm/pcparchive.py
The current code always includes the start and end archives when processing a
job. These archives are selected based on the resource, hostname and
local_job_id. This is an issue on resources where the local_job_id is not a unique identifier
for the job [1]. In this scenario the job start and end archives for all jobs with the
same hostname and local_job_id are processed.
This change restricts the time window of job archives to be within 30 seconds of
the job start/end as reported by the resource manager. The 30 second value was chosen
as it is the default recommended periodic collection period.
[1] For example this can happen if a job is requeued due to a node fail or if the
local_job_id is reset by a system administrator.
=> Restrict job start end PCP archives by time.

src/supremm/indexarchives.py
Now support archives organised in a directory structure like:
```bash
[top_dir]/[YYYY]/[MM]/[HOSTNAME]/[YYYY-MM-DD]
```
=> Add support for new archive layout

src/supremm/scripthelpers.py
This is needed for recent versions of the MySQLDB driver 1.2.5
=> Add local_infile flag to MySQL connection

src/supremm/plugins/GpuPower.py, src/supremm/plugins/IpmiPower.py, src/supremm/statistics.py
Added plugins for energy consumption metrics from Ipmi and GPU data sources.
=> Added power metrics

src/supremm/assets/mongo_setup.js, src/supremm/plugins/PowerUsageTimeseries.py
Also update the schema definition.
=> Add power usage timeseries plugin

src/supremm/pcparchive.py, src/supremm/summarize_jobs.py
This pull request cherry picks @treydock changes related to job directory management. 
This is a subset of the various updates in #215, which is being split into multiple pulls for ease of change management.
=> Update error handling of temporary job directory management

Dockerfile
Some sort of upstream updates broke the build.
=> Pin version of configparser.

src/supremm/plugins/CpuPerfCounters.py
Improve the chances of getting cpu counter data summarized.
=> Improve cpu perf counter error handling.

src/supremm/errors.py, src/supremm/plugins/CgroupMemTimeseries.py, src/supremm/plugins/CgroupMemory.py, src/supremm/preprocessors/Proc.py, src/supremm/proc_common.py, src/supremm/supremm_testharness.py, src/supremm/xdmodaccount.py
This pull request includes the last of the incremental changes from #215. This supercedes #150 and #155
=> Merge treydock master

src/supremm/errors.py, src/supremm/ingest_jobscripts.py, src/supremm/pcparchive.py, src/supremm/plugins/CgroupMemTimeseries.py, src/supremm/plugins/CgroupMemory.py, src/supremm/preprocessors/Proc.py, src/supremm/proc_common.py, src/supremm/summarize_jobs.py, src/supremm/xdmodaccount.py
This would replace #155 and #150 .
The main difference from those pull requests is a few minor tweaks to avoid file and directory operations that would normally cause errors.
=> Several changes being used at Ohio Supercomputer Center

src/supremm/config.py
This includes @treydock  changes in pull request #236. In this version of the update the existing config file search order is preserved.
=> Allow defining path to config via SUPREMM_CONFIG_DIR  - updated

src/supremm/xdmodaccount.py
This is pull request #235 but with a small change to fix a bug found during testing against XDMoD 8.0
=> Add support for adding GPU count to account summarization w/ patch

src/supremm/xdmodaccount.py
Collect GPU count so it can be put into summarization JSON.  This I believe will populate https://github.com/ubccr/xdmod-supremm/pull/262 and be used by https://github.com/ubccr/xdmod-supremm/pull/264
=> Add support for adding GPU count to account summarization

src/supremm/supremm_testharness.py
Add optional `-j --job-id` and `-a --acct-uid` arguments to specify `job_id` and `acct['uid']` values in the testharness.
=> Add options to specify id/uid to testharness

src/supremm/config.py, src/supremm/supremmconf.py
This PR improves the capabilities of the configuration check utility in supremmconf.py.
supremmconf.py
1.) Added debug flag
2.) Added flag to specify configuration path
3.) Can now print entire configuration
4.) Better handling for invalid sections or items
config.py
1.) Added __str__ method for easier printing
Tested on Rocky 8, Python 3.6.8
=> Updates to the configuration check utility.

src/supremm/config.py, src/supremm/supremmconf.py
=> Revert "Updates to the configuration check utility."

src/supremm/config.py, src/supremm/supremmconf.py
This PR is the Python 2.7 equivalent to [this PR](https://github.com/ubccr/supremm/pull/257).
=> Updates to the configuration check utility for Python 2.7

CHANGELOG.md, README.md
These changes update the CHANGELOG for the release of v2.0.0
=> CHANGELOG and README updates

setup.cfg
This PR edits the build version for the RPM.
=> Bump version number
